CREATE TABLE courses (
    course_id SERIAL PRIMARY KEY,
    course_name VARCHAR,
    department VARCHAR,
    credits INT,
    professor VARCHAR,
    is_elective BOOLEAN
)

INSERT INTO courses (course_name, department, credits, professor, is_elective) VALUES
('Introduction to Computer Science', 'Computer Science', 4, 'Dr. Sharma', FALSE),
('Calculus I', 'Mathematics', 3, 'Prof. Patel', FALSE),
('World History', 'History', 3, NULL, TRUE),
('Organic Chemistry', 'Chemistry', 4, 'Dr. Gupta', FALSE),
('Principles of Economics', 'Economics', 3, 'Prof. Reddy', TRUE),
('English Literature', 'English', 3, 'Dr. Iyer', FALSE),
('Data Structures', 'Computer Science', 4, 'Prof. Joshi', FALSE),
('Quantum Physics', 'Physics', 4, NULL, FALSE),
('Financial Accounting', 'Business', 3, 'Prof. Malhotra', TRUE),
('Artificial Intelligence', 'Computer Science', 4, 'Dr. Chatterjee', FALSE),
('Microbiology', 'Biology', 4, 'Dr. Banerjee', FALSE),
('Linear Algebra', 'Mathematics', 3, 'Prof. Rao', FALSE),
('Political Science', 'Political Science', 3, 'Dr. Sinha', TRUE),
('Digital Marketing', 'Business', 3, NULL, TRUE),
('Environmental Science', 'Environmental Studies', 3, 'Prof. Das', FALSE),
('French Language', 'Languages', 2, 'Dr. Dubois', TRUE),
('Machine Learning', NULL, 4, 'Prof. Kumar', FALSE),
('Ancient Philosophy', 'Philosophy', 3, 'Dr. Acharya', TRUE),
('Statistics', 'Mathematics', 3, 'Prof. Verma', FALSE),
('Biochemistry', 'Chemistry', 4, NULL, FALSE),
('Creative Writing', 'English', 2, 'Prof. Nair', TRUE),
('Database Systems', 'Computer Science', 4, 'Dr. Menon', FALSE),
('Macroeconomics', 'Economics', 3, 'Prof. Sengupta', FALSE),
('Human Anatomy', 'Biology', 4, 'Dr. Choudhary', FALSE),
('Graphic Design', 'Arts', 2, 'Prof. Kapoor', TRUE),
('Operating Systems', 'Computer Science', 4, 'Dr. Saxena', FALSE),
('Sociology', 'Social Sciences', 3, 'Prof. Mehta', TRUE),
('Thermodynamics', 'Physics', 4, 'Dr. Bose', FALSE),
('Corporate Finance', 'Business', 3, NULL, FALSE),
('Spanish Language', 'Languages', 2, 'Prof. Garcia', TRUE),
('Computer Networks', 'Computer Science', 4, 'Dr. Khanna', FALSE),
('Cognitive Psychology', 'Psychology', 3, 'Prof. Anand', TRUE),
('Differential Equations', 'Mathematics', 3, 'Dr. Tripathi', FALSE),
('Genetics', 'Biology', 4, 'Prof. Mukherjee', FALSE),
('Public Speaking', 'Communication', 2, 'Dr. Naidu', TRUE),
('Software Engineering', 'Computer Science', 4, 'Prof. Desai', FALSE),
('International Relations', 'Political Science', 3, 'Dr. Chawla', TRUE),
('Electromagnetism', 'Physics', 4, 'Prof. Bajaj', FALSE),
('Marketing Management', 'Business', 3, NULL, FALSE)

select * from courses  
